#spring.application.name=OnlineCinema
server:
    port: 8080
jwt:
    secret: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
    lifetime: 25m
spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: 123
    flyway:
        enabled: true
        locations:
            - db.migration

